---
name: 'test_deploy'

'on':
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  forge_deploy:

    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout repo'
        uses: 'actions/checkout@v3'

      - name: 'Set up Ruby'
        uses: 'ruby/setup-ruby@v1.137.2'
        env:
          BUNDLE_SILENCE_ROOT_WARNING: '1'
          BUNDLE_WITH: 'development'
        with:
          bundler-cache: true
          ruby-version: '2.7'
          rubygems: 'latest'

      - name: 'Module prep and build'
        run: |
          bundle exec pdk build
          bundle exec pdk release prep --skip-changelog --skip-documentation --force
